service: mes-result-service

provider:
  name: aws
  runtime: nodejs20.x

functions:
  postResult:
    handler: src/functions/postResult/framework/handler.handler
    events:
      - http:
          path: test-results
          method: post

  getNextUploadBatch:
    handler: src/functions/getNextUploadBatch/framework/handler.handler
    events:
      - http:
          path: test-results/upload
          method: get

  updateUploadStatus:
    handler: src/functions/updateUploadStatus/framework/handler.handler
    events:
      - http:
          path: test-results/{appRef}/upload
          method: put

  searchResults:
    handler: src/functions/searchResults/framework/handler.handler
    events:
      - http:
          path: test-results
          method: get

  searchExaminerRecords:
    handler: src/functions/searchExaminerRecords/framework/handler.handler
    events:
      - http:
          path: test-results/search-examiner-records
          method: get

  getResult:
    handler: src/functions/getResult/framework/handler.handler
    events:
      - http:
          path: test-results/{appRef}/{staffNumber}
          method: get

  getRegeneratedEmails:
    handler: src/functions/getRegeneratedEmails/framework/handler.handler
    events:
      - http:
          path: test-results/regeneratedemails/{appRef}
          method: get

  retryProcessing:
    handler: src/functions/retryProcessing/framework/handler.handler
    events:
      - http:
          path: test-results/retry
          method: get

  deleteTestResult:
    handler: src/functions/deleteTestResult/framework/handler.handler
    events:
      - http:
          path: test-results/delete
          method: put

custom:
  webpack:
    webpackConfig: 'webpack-sls-offline.config.js'

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline
