service: mes-result-service

provider:
  name: aws
  runtime: nodejs16.x

functions:
  postResult:
    handler: src/functions/postResult/framework/handler.handler
    events:
      - http:
          path: test-results
          method: post

  getNextUploadBatch:
    handler: src/functions/getNextUploadBatch/framework/handler.handler
    events:
      - http:
          path: test-results/upload
          method: get

  updateUploadStatus:
    handler: src/functions/updateUploadStatus/framework/handler.handler
    events:
      - http:
          path: test-results/{appRef}/upload
          method: put

  searchResults:
    handler: src/functions/searchResults/framework/handler.handler
    events:
      - http:
          path: test-results
          method: get

  getResult:
    handler: src/functions/getResult/framework/handler.handler
    events:
      - http:
          path: test-results/{appRef}/{staffNumber}
          method: get

  getRegeneratedEmails:
    handler: src/functions/getRegeneratedEmails/framework/handler.handler
    events:
      - http:
          path: test-results/regeneratedemails/{appRef}
          method: get

  retryProcessing:
    handler: src/functions/retryProcessing/framework/handler.handler
    events:
      - http:
          path: test-results/retry
          method: get

  deleteTestResult:
    handler: src/functions/deleteTestResult/framework/handler.handler
    events:
      - http:
          path: test-results/delete
          method: put

  updateDuplicatePassCertificates:
    handler: src/functions/updateDuplicatePassCertificates/framework/handler.handler
    events:
      - http:
          path: pass-certificate/duplicate-certificates
          method: put

  getMissingPassCertificates:
    handler: src/functions/getMissingPassCertificates/framework/handler.handler
    events:
      - http:
          path: pass-certificate/missing-certificates
          method: get

  postSpoiledPassCertificates:
    handler: src/functions/postSpoiledPassCertificates/framework/handler.handler
    events:
      - http:
          path: pass-certificate/spoiled-certificates
          method: post

custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
  webpack:
    webpackConfig: 'webpack-sls-offline.config.js'

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline
