service: mes-result-service

provider:
  name: aws
  runtime: nodejs16.x

functions:
  postResult:
    handler: src/functions/postResult/framework/handler.handler
    events:
      - http:
          path: test-result
          method: post

  getNextUploadBatch:
    handler: src/functions/getNextUploadBatch/framework/handler.handler
    events:
      - http:
          path: test-result/upload
          method: get

  updateUploadStatus:
    handler: src/functions/updateUploadStatus/framework/handler.handler
    events:
      - http:
          path: test-result/{appref}/upload
          method: put

  searchResults:
    handler: src/functions/searchResults/framework/handler.handler
    events:
      - http:
          path: test-result
          method: get

  getResult:
    handler: src/functions/getResult/framework/handler.handler
    events:
      - http:
          path: test-result/{appref}/{staffnumber}
          method: get

  retryProcessing:
    handler: src/functions/retryProcessing/framework/handler.handler
    events:
      - http:
          path: test-result/retry
          method: get

  deleteTestResult:
    handler: src/functions/deleteTestResult/framework/handler.handler
    events:
      - http:
          path: test-result/delete
          method: put

  missingCertificates:
    handler: src/functions/missingCertificates/framework/handler.handler
    events:
      - http:
          path: missingCertificates
          method: put
custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
  webpack:
    webpackConfig: 'webpack-sls-offline.config.js'

plugins:
  - serverless-webpack
  - serverless-offline
