version: '3.9'
services:
  des-result-service-result-db:
    image: mysql:8.0.32
    environment:
      MYSQL_DATABASE: results
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_USER: results_user
      MYSQL_PASSWORD: Pa55word1
    volumes:
      - './results_database/010-database_creation.sql:/docker-entrypoint-initdb.d/010-database_creation.sql'
      - './results_database/020-test_results_table_test-data.sql:/docker-entrypoint-initdb.d/020-test_results_table_test-data.sql'
    ports:
      - '3306:3306'
