version: '3'
services:
  des-result-service-result-db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: results
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_USER: results_user
      MYSQL_PASSWORD: Pa55word1
    volumes:
      - './010-schema.sql:/docker-entrypoint-initdb.d/010-schema.sql'
      - './020-test-data-sproc.sql:/docker-entrypoint-initdb.d/020-test-data-sproc.sql'
      - './030-test-data.sql:/docker-entrypoint-initdb.d/030-test-data.sql'
    ports:
      - '3306:3306'
